version: '3.1'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=product
      - POSTGRES_PASSWORD=1q2w3e4r
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'

